.PHONY: clean All

All:
	@echo "----------Building project:[ Question03 - Debug ]----------"
	@cd "Question03" && "$(MAKE)" -f  "Question03.mk"
clean:
	@echo "----------Cleaning project:[ Question03 - Debug ]----------"
	@cd "Question03" && "$(MAKE)" -f  "Question03.mk" clean
