.PHONY: clean All

All:
	@echo "----------Building project:[ Question12 - Debug ]----------"
	@cd "Question12" && "$(MAKE)" -f  "Question12.mk"
clean:
	@echo "----------Cleaning project:[ Question12 - Debug ]----------"
	@cd "Question12" && "$(MAKE)" -f  "Question12.mk" clean
