.PHONY: clean All

All:
	@echo "----------Building project:[ question10 - Debug ]----------"
	@cd "question10" && "$(MAKE)" -f  "question10.mk"
clean:
	@echo "----------Cleaning project:[ question10 - Debug ]----------"
	@cd "question10" && "$(MAKE)" -f  "question10.mk" clean
