.PHONY: clean All

All:
	@echo "----------Building project:[ Question13 - Debug ]----------"
	@cd "Question13" && "$(MAKE)" -f  "Question13.mk"
clean:
	@echo "----------Cleaning project:[ Question13 - Debug ]----------"
	@cd "Question13" && "$(MAKE)" -f  "Question13.mk" clean
