.PHONY: clean All

All:
	@echo "----------Building project:[ question13 - Debug ]----------"
	@cd "question13" && "$(MAKE)" -f  "question13.mk"
clean:
	@echo "----------Cleaning project:[ question13 - Debug ]----------"
	@cd "question13" && "$(MAKE)" -f  "question13.mk" clean
