.PHONY: clean All

All:
	@echo "----------Building project:[ Question09 - Debug ]----------"
	@cd "Question09" && "$(MAKE)" -f  "Question09.mk"
clean:
	@echo "----------Cleaning project:[ Question09 - Debug ]----------"
	@cd "Question09" && "$(MAKE)" -f  "Question09.mk" clean
